<?php
echo"<section id='contact'>";
 echo"<h3>Contact us</h3>";
  echo"<p> P: +61 396 678 7878 <br/> 34 Jhonston st, Melbourne, Australia</p>";
  echo"<p><a href='mailto:info@flighthub.com.au'>info@flighthub.com.au</a></p>";
echo"</section>";
echo"<section class='askhub'>";
  echo"<h3>Ask Hub </h3>";
    echo"<form method='post' action='https://mercury.swin.edu.au/it000000/formtest.php'>";
    echo"<input type='text' class='askbox' placeholder='Type your question' name='askhub'>";
    echo"<button type='submit'><i class='fa fa-arrow-right'></i></button>";
    echo"</form>";
echo"</section>";
  echo"<footer id='footerbar'>";
    echo"<p>&#169;FlightHub Australia Pty Ltd. ABN: 42 897 900 675. &nbsp;<a href='product.php#contact'></a></p>";
  echo"</footer>";
?>
